// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcdnzymmwogeypwkriag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZG56eW1td29nZXlwd2tyaWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1Mzk0NTcsImV4cCI6MjA1MTExNTQ1N30.rc4hFiSbLHEJrq1WjSiCPbgAnz_h1UGwNNfRh5LljUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);